version: "3.9"
services:
  web:
    build: .
    restart: always
    stdin_open: true
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/code
